/* Auto-generated from scheduler.md — Türkiye saatleri (UK +2sa) */
var WC_MATCHES = [
  {"d": "2026-06-11", "t": "22:00", "g": "Grup A", "h": "Meksika", "hc": "MEX", "hf": "icons/mexico.png", "a": "Güney Afrika", "ac": "RSA", "af": "icons/south-africa.png", "city": "Mexico City", "tr": false},
  {"d": "2026-06-12", "t": "05:00", "g": "Grup A", "h": "Güney Kore", "hc": "KOR", "hf": "icons/south-korea.png", "a": "Çekya", "ac": "CZE", "af": "icons/czchehia.png", "city": "Zapopan", "tr": false},
  {"d": "2026-06-12", "t": "22:00", "g": "Grup B", "h": "Kanada", "hc": "CAN", "hf": "icons/canada.png", "a": "Bosna Hersek", "ac": "BIH", "af": "icons/bosnia-and-herzegovina.png", "city": "Toronto", "tr": false},
  {"d": "2026-06-13", "t": "04:00", "g": "Grup D", "h": "ABD", "hc": "USA", "hf": "icons/united-states.png", "a": "Paraguay", "ac": "PAR", "af": "icons/paraguay.png", "city": "Los Angeles", "tr": false},
  {"d": "2026-06-13", "t": "22:00", "g": "Grup B", "h": "Katar", "hc": "QAT", "hf": "icons/qatar.png", "a": "İsviçre", "ac": "SUI", "af": "icons/switzerland.png", "city": "Santa Clara", "tr": false},
  {"d": "2026-06-14", "t": "01:00", "g": "Grup C", "h": "Brezilya", "hc": "BRA", "hf": "icons/brazil.png", "a": "Fas", "ac": "MAR", "af": "icons/morocco.png", "city": "New Jersey", "tr": false},
  {"d": "2026-06-14", "t": "04:00", "g": "Grup C", "h": "Haiti", "hc": "HAI", "hf": "icons/haiti.png", "a": "İskoçya", "ac": "SCO", "af": "icons/scotland.png", "city": "Foxborough", "tr": false},
  {"d": "2026-06-14", "t": "07:00", "g": "Grup D", "h": "Avustralya", "hc": "AUS", "hf": "icons/australia.png", "a": "Türkiye", "ac": "TUR", "af": "icons/turkey.png", "city": "Vancouver", "tr": true},
  {"d": "2026-06-14", "t": "20:00", "g": "Grup E", "h": "Almanya", "hc": "GER", "hf": "icons/germany.png", "a": "Curaçao", "ac": "CUW", "af": "icons/curacao.png", "city": "Houston", "tr": false},
  {"d": "2026-06-14", "t": "23:00", "g": "Grup F", "h": "Hollanda", "hc": "NED", "hf": "icons/netherlands.png", "a": "Japonya", "ac": "JPN", "af": "icons/japan.png", "city": "Arlington", "tr": false},
  {"d": "2026-06-15", "t": "02:00", "g": "Grup E", "h": "Fildişi Sahili", "hc": "CIV", "hf": "icons/cote-d.png", "a": "Ekvador", "ac": "ECU", "af": "icons/ecuador.png", "city": "Philadelphia", "tr": false},
  {"d": "2026-06-15", "t": "05:00", "g": "Grup F", "h": "İsveç", "hc": "SWE", "hf": "icons/sweeden.png", "a": "Tunus", "ac": "TUN", "af": "icons/tunisia.png", "city": "Guadalupe", "tr": false},
  {"d": "2026-06-15", "t": "19:00", "g": "Grup H", "h": "İspanya", "hc": "ESP", "hf": "icons/spain.png", "a": "Cabo Verde", "ac": "CPV", "af": "icons/cabo-verde.png", "city": "Atlanta", "tr": false},
  {"d": "2026-06-15", "t": "22:00", "g": "Grup G", "h": "Belçika", "hc": "BEL", "hf": "icons/belgium.png", "a": "Mısır", "ac": "EGY", "af": "icons/egypt.png", "city": "Seattle", "tr": false},
  {"d": "2026-06-16", "t": "01:00", "g": "Grup H", "h": "Suudi Arabistan", "hc": "KSA", "hf": "icons/saudi-arabia.png", "a": "Uruguay", "ac": "URU", "af": "icons/uruguay.png", "city": "Miami", "tr": false},
  {"d": "2026-06-16", "t": "04:00", "g": "Grup G", "h": "İran", "hc": "IRN", "hf": "icons/iran.png", "a": "Yeni Zelanda", "ac": "NZL", "af": "icons/new-zealand.png", "city": "Los Angeles", "tr": false},
  {"d": "2026-06-16", "t": "22:00", "g": "Grup I", "h": "Fransa", "hc": "FRA", "hf": "icons/france.png", "a": "Senegal", "ac": "SEN", "af": "icons/senegal-flag.png", "city": "New Jersey", "tr": false},
  {"d": "2026-06-17", "t": "01:00", "g": "Grup I", "h": "Irak", "hc": "IRQ", "hf": "icons/iraq.png", "a": "Norveç", "ac": "NOR", "af": "icons/norway.png", "city": "Foxborough", "tr": false},
  {"d": "2026-06-17", "t": "04:00", "g": "Grup J", "h": "Arjantin", "hc": "ARG", "hf": "icons/argentina.png", "a": "Cezayir", "ac": "ALG", "af": "icons/algeria.png", "city": "Kansas City", "tr": false},
  {"d": "2026-06-17", "t": "07:00", "g": "Grup J", "h": "Avusturya", "hc": "AUT", "hf": "icons/austria.png", "a": "Ürdün", "ac": "JOR", "af": "icons/jordan.png", "city": "Santa Clara", "tr": false},
  {"d": "2026-06-17", "t": "20:00", "g": "Grup K", "h": "Portekiz", "hc": "POR", "hf": "icons/portugal.png", "a": "DK Kongo", "ac": "COD", "af": "icons/dr-congo.png", "city": "Houston", "tr": false},
  {"d": "2026-06-17", "t": "23:00", "g": "Grup L", "h": "İngiltere", "hc": "ENG", "hf": "icons/england.png", "a": "Hırvatistan", "ac": "CRO", "af": "icons/croatia.png", "city": "Arlington", "tr": false},
  {"d": "2026-06-18", "t": "02:00", "g": "Grup L", "h": "Gana", "hc": "GHA", "hf": "icons/ghana.png", "a": "Panama", "ac": "PAN", "af": "icons/panama.png", "city": "Toronto", "tr": false},
  {"d": "2026-06-18", "t": "05:00", "g": "Grup K", "h": "Özbekistan", "hc": "UZB", "hf": "icons/uzbekistan.png", "a": "Kolombiya", "ac": "COL", "af": "icons/colombia.png", "city": "Mexico City", "tr": false},
  {"d": "2026-06-18", "t": "19:00", "g": "Grup A", "h": "Çekya", "hc": "CZE", "hf": "icons/czchehia.png", "a": "Güney Afrika", "ac": "RSA", "af": "icons/south-africa.png", "city": "Atlanta", "tr": false},
  {"d": "2026-06-18", "t": "22:00", "g": "Grup B", "h": "İsviçre", "hc": "SUI", "hf": "icons/switzerland.png", "a": "Bosna Hersek", "ac": "BIH", "af": "icons/bosnia-and-herzegovina.png", "city": "Los Angeles", "tr": false},
  {"d": "2026-06-19", "t": "01:00", "g": "Grup B", "h": "Kanada", "hc": "CAN", "hf": "icons/canada.png", "a": "Katar", "ac": "QAT", "af": "icons/qatar.png", "city": "Vancouver", "tr": false},
  {"d": "2026-06-19", "t": "04:00", "g": "Grup A", "h": "Meksika", "hc": "MEX", "hf": "icons/mexico.png", "a": "Güney Kore", "ac": "KOR", "af": "icons/south-korea.png", "city": "Zapopan", "tr": false},
  {"d": "2026-06-19", "t": "22:00", "g": "Grup D", "h": "ABD", "hc": "USA", "hf": "icons/united-states.png", "a": "Avustralya", "ac": "AUS", "af": "icons/australia.png", "city": "Seattle", "tr": false},
  {"d": "2026-06-20", "t": "01:00", "g": "Grup C", "h": "İskoçya", "hc": "SCO", "hf": "icons/scotland.png", "a": "Fas", "ac": "MAR", "af": "icons/morocco.png", "city": "Foxborough", "tr": false},
  {"d": "2026-06-20", "t": "03:30", "g": "Grup C", "h": "Brezilya", "hc": "BRA", "hf": "icons/brazil.png", "a": "Haiti", "ac": "HAI", "af": "icons/haiti.png", "city": "Philadelphia", "tr": false},
  {"d": "2026-06-20", "t": "06:00", "g": "Grup D", "h": "Türkiye", "hc": "TUR", "hf": "icons/turkey.png", "a": "Paraguay", "ac": "PAR", "af": "icons/paraguay.png", "city": "Santa Clara", "tr": true},
  {"d": "2026-06-20", "t": "20:00", "g": "Grup A", "h": "Hollanda", "hc": "NED", "hf": "icons/netherlands.png", "a": "İsveç", "ac": "SWE", "af": "icons/sweeden.png", "city": "Houston", "tr": false},
  {"d": "2026-06-20", "t": "23:00", "g": "Grup E", "h": "Almanya", "hc": "GER", "hf": "icons/germany.png", "a": "Fildişi Sahili", "ac": "CIV", "af": "icons/cote-d.png", "city": "Toronto", "tr": false},
  {"d": "2026-06-21", "t": "03:00", "g": "Grup E", "h": "Ekvador", "hc": "ECU", "hf": "icons/ecuador.png", "a": "Curaçao", "ac": "CUW", "af": "icons/curacao.png", "city": "Kansas City", "tr": false},
  {"d": "2026-06-21", "t": "07:00", "g": "Grup F", "h": "Tunus", "hc": "TUN", "hf": "icons/tunisia.png", "a": "Japonya", "ac": "JPN", "af": "icons/japan.png", "city": "Guadalupe", "tr": false},
  {"d": "2026-06-21", "t": "19:00", "g": "Grup H", "h": "İspanya", "hc": "ESP", "hf": "icons/spain.png", "a": "Suudi Arabistan", "ac": "KSA", "af": "icons/saudi-arabia.png", "city": "Atlanta", "tr": false},
  {"d": "2026-06-21", "t": "22:00", "g": "Grup G", "h": "Belçika", "hc": "BEL", "hf": "icons/belgium.png", "a": "İran", "ac": "IRN", "af": "icons/iran.png", "city": "Los Angeles", "tr": false},
  {"d": "2026-06-22", "t": "01:00", "g": "Grup H", "h": "Uruguay", "hc": "URU", "hf": "icons/uruguay.png", "a": "Cabo Verde", "ac": "CPV", "af": "icons/cabo-verde.png", "city": "Miami", "tr": false},
  {"d": "2026-06-22", "t": "04:00", "g": "Grup G", "h": "Yeni Zelanda", "hc": "NZL", "hf": "icons/new-zealand.png", "a": "Mısır", "ac": "EGY", "af": "icons/egypt.png", "city": "Vancouver", "tr": false},
  {"d": "2026-06-22", "t": "20:00", "g": "Grup J", "h": "Arjantin", "hc": "ARG", "hf": "icons/argentina.png", "a": "Avusturya", "ac": "AUT", "af": "icons/austria.png", "city": "Arlington", "tr": false},
  {"d": "2026-06-23", "t": "00:00", "g": "Grup I", "h": "Fransa", "hc": "FRA", "hf": "icons/france.png", "a": "Irak", "ac": "IRQ", "af": "icons/iraq.png", "city": "Philadelphia", "tr": false},
  {"d": "2026-06-23", "t": "03:00", "g": "Grup I", "h": "Norveç", "hc": "NOR", "hf": "icons/norway.png", "a": "Senegal", "ac": "SEN", "af": "icons/senegal-flag.png", "city": "Toronto", "tr": false},
  {"d": "2026-06-23", "t": "06:00", "g": "Grup J", "h": "Ürdün", "hc": "JOR", "hf": "icons/jordan.png", "a": "Cezayir", "ac": "ALG", "af": "icons/algeria.png", "city": "Santa Clara", "tr": false},
  {"d": "2026-06-23", "t": "20:00", "g": "Grup K", "h": "Portekiz", "hc": "POR", "hf": "icons/portugal.png", "a": "Özbekistan", "ac": "UZB", "af": "icons/uzbekistan.png", "city": "Houston", "tr": false},
  {"d": "2026-06-23", "t": "23:00", "g": "Grup L", "h": "İngiltere", "hc": "ENG", "hf": "icons/england.png", "a": "Gana", "ac": "GHA", "af": "icons/ghana.png", "city": "Foxborough", "tr": false},
  {"d": "2026-06-24", "t": "02:00", "g": "Grup L", "h": "Panama", "hc": "PAN", "hf": "icons/panama.png", "a": "Hırvatistan", "ac": "CRO", "af": "icons/croatia.png", "city": "Foxborough", "tr": false},
  {"d": "2026-06-24", "t": "05:00", "g": "Grup K", "h": "Kolombiya", "hc": "COL", "hf": "icons/colombia.png", "a": "DK Kongo", "ac": "COD", "af": "icons/dr-congo.png", "city": "Zapopan", "tr": false},
  {"d": "2026-06-24", "t": "22:00", "g": "Grup B", "h": "İsviçre", "hc": "SUI", "hf": "icons/switzerland.png", "a": "Kanada", "ac": "CAN", "af": "icons/canada.png", "city": "Vancouver", "tr": false},
  {"d": "2026-06-24", "t": "22:00", "g": "Grup B", "h": "Bosna Hersek", "hc": "BIH", "hf": "icons/bosnia-and-herzegovina.png", "a": "Katar", "ac": "QAT", "af": "icons/qatar.png", "city": "Seattle", "tr": false},
  {"d": "2026-06-25", "t": "01:00", "g": "Grup C", "h": "Fas", "hc": "MAR", "hf": "icons/morocco.png", "a": "Haiti", "ac": "HAI", "af": "icons/haiti.png", "city": "Atlanta", "tr": false},
  {"d": "2026-06-25", "t": "01:00", "g": "Grup C", "h": "İskoçya", "hc": "SCO", "hf": "icons/scotland.png", "a": "Brezilya", "ac": "BRA", "af": "icons/brazil.png", "city": "Miami", "tr": false},
  {"d": "2026-06-25", "t": "04:00", "g": "Grup A", "h": "Güney Afrika", "hc": "RSA", "hf": "icons/south-africa.png", "a": "Güney Kore", "ac": "KOR", "af": "icons/south-korea.png", "city": "Guadalupe", "tr": false},
  {"d": "2026-06-25", "t": "04:00", "g": "Grup A", "h": "Çekya", "hc": "CZE", "hf": "icons/czchehia.png", "a": "Meksika", "ac": "MEX", "af": "icons/mexico.png", "city": "Mexico City", "tr": false},
  {"d": "2026-06-25", "t": "23:00", "g": "Grup E", "h": "Curaçao", "hc": "CUW", "hf": "icons/curacao.png", "a": "Fildişi Sahili", "ac": "CIV", "af": "icons/cote-d.png", "city": "Philadelphia", "tr": false},
  {"d": "2026-06-25", "t": "23:00", "g": "Grup E", "h": "Ekvador", "hc": "ECU", "hf": "icons/ecuador.png", "a": "Almanya", "ac": "GER", "af": "icons/germany.png", "city": "New Jersey", "tr": false},
  {"d": "2026-06-26", "t": "02:00", "g": "Grup F", "h": "Tunus", "hc": "TUN", "hf": "icons/tunisia.png", "a": "Hollanda", "ac": "NED", "af": "icons/netherlands.png", "city": "Kansas City", "tr": false},
  {"d": "2026-06-26", "t": "02:00", "g": "Grup F", "h": "Japonya", "hc": "JPN", "hf": "icons/japan.png", "a": "İsveç", "ac": "SWE", "af": "icons/sweeden.png", "city": "Arlington", "tr": false},
  {"d": "2026-06-26", "t": "05:00", "g": "Grup D", "h": "Türkiye", "hc": "TUR", "hf": "icons/turkey.png", "a": "ABD", "ac": "USA", "af": "icons/united-states.png", "city": "Los Angeles", "tr": true},
  {"d": "2026-06-26", "t": "05:00", "g": "Grup D", "h": "Paraguay", "hc": "PAR", "hf": "icons/paraguay.png", "a": "Avustralya", "ac": "AUS", "af": "icons/australia.png", "city": "Santa Clara", "tr": false},
  {"d": "2026-06-26", "t": "22:00", "g": "Grup I", "h": "Norveç", "hc": "NOR", "hf": "icons/norway.png", "a": "Fransa", "ac": "FRA", "af": "icons/france.png", "city": "Foxborough", "tr": false},
  {"d": "2026-06-26", "t": "22:00", "g": "Grup I", "h": "Senegal", "hc": "SEN", "hf": "icons/senegal-flag.png", "a": "Irak", "ac": "IRQ", "af": "icons/iraq.png", "city": "Toronto", "tr": false},
  {"d": "2026-06-27", "t": "03:00", "g": "Grup H", "h": "Cabo Verde", "hc": "CPV", "hf": "icons/cabo-verde.png", "a": "Suudi Arabistan", "ac": "KSA", "af": "icons/saudi-arabia.png", "city": "Houston", "tr": false},
  {"d": "2026-06-27", "t": "03:00", "g": "Grup H", "h": "Uruguay", "hc": "URU", "hf": "icons/uruguay.png", "a": "İspanya", "ac": "ESP", "af": "icons/spain.png", "city": "Zapopan", "tr": false},
  {"d": "2026-06-27", "t": "06:00", "g": "Grup G", "h": "Yeni Zelanda", "hc": "NZL", "hf": "icons/new-zealand.png", "a": "Belçika", "ac": "BEL", "af": "icons/belgium.png", "city": "Vancouver", "tr": false},
  {"d": "2026-06-27", "t": "06:00", "g": "Grup G", "h": "Mısır", "hc": "EGY", "hf": "icons/egypt.png", "a": "İran", "ac": "IRN", "af": "icons/iran.png", "city": "Seattle", "tr": false},
  {"d": "2026-06-28", "t": "00:00", "g": "Grup L", "h": "Panama", "hc": "PAN", "hf": "icons/panama.png", "a": "İngiltere", "ac": "ENG", "af": "icons/england.png", "city": "New Jersey", "tr": false},
  {"d": "2026-06-28", "t": "00:00", "g": "Grup L", "h": "Hırvatistan", "hc": "CRO", "hf": "icons/croatia.png", "a": "Gana", "ac": "GHA", "af": "icons/ghana.png", "city": "Philadelphia", "tr": false},
  {"d": "2026-06-28", "t": "02:30", "g": "Grup K", "h": "Kolombiya", "hc": "COL", "hf": "icons/colombia.png", "a": "Portekiz", "ac": "POR", "af": "icons/portugal.png", "city": "Miami", "tr": false},
  {"d": "2026-06-28", "t": "02:30", "g": "Grup K", "h": "DK Kongo", "hc": "COD", "hf": "icons/dr-congo.png", "a": "Özbekistan", "ac": "UZB", "af": "icons/uzbekistan.png", "city": "Atlanta", "tr": false},
  {"d": "2026-06-28", "t": "05:00", "g": "Grup J", "h": "Cezayir", "hc": "ALG", "hf": "icons/algeria.png", "a": "Avusturya", "ac": "AUT", "af": "icons/austria.png", "city": "Kansas City", "tr": false},
  {"d": "2026-06-28", "t": "05:00", "g": "Grup J", "h": "Ürdün", "hc": "JOR", "hf": "icons/jordan.png", "a": "Arjantin", "ac": "ARG", "af": "icons/argentina.png", "city": "Arlington", "tr": false},
  {"d": "2026-06-28", "t": "22:00", "g": "Son 32 · Maç 73", "h": "Güney Afrika", "hc": "RSA", "hf": "icons/south-africa.png", "a": "Kanada", "ac": "CAN", "af": "icons/canada.png", "city": "Los Angeles", "tr": false},
  {"d": "2026-06-29", "t": "20:00", "g": "Son 32 · Maç 76", "h": "Brezilya", "hc": "BRA", "hf": "icons/brazil.png", "a": "Japonya", "ac": "JPN", "af": "icons/japan.png", "city": "Houston", "tr": false},
  {"d": "2026-06-29", "t": "23:30", "g": "Son 32 · Maç 74", "h": "Almanya", "hc": "GER", "hf": "icons/germany.png", "a": "Paraguay", "ac": "PAR", "af": "icons/paraguay.png", "city": "Foxborough", "tr": false},
  {"d": "2026-06-30", "t": "04:00", "g": "Son 32 · Maç 75", "h": "Hollanda", "hc": "NED", "hf": "icons/netherlands.png", "a": "Fas", "ac": "MAR", "af": "icons/morocco.png", "city": "Guadalupe", "tr": false},
  {"d": "2026-06-30", "t": "20:00", "g": "Son 32 · Maç 78", "h": "Fildişi Sahili", "hc": "CIV", "hf": "icons/cote-d.png", "a": "Norveç", "ac": "NOR", "af": "icons/norway.png", "city": "Arlington", "tr": false},
  {"d": "2026-07-01", "t": "00:00", "g": "Son 32 · Maç 77", "h": "Fransa", "hc": "FRA", "hf": "icons/france.png", "a": "İsveç", "ac": "SWE", "af": "icons/sweeden.png", "city": "New Jersey", "tr": false},
  {"d": "2026-07-01", "t": "04:00", "g": "Son 32 · Maç 79", "h": "Meksika", "hc": "MEX", "hf": "icons/mexico.png", "a": "Ekvador", "ac": "ECU", "af": "icons/ecuador.png", "city": "Mexico City", "tr": false},
  {"d": "2026-07-01", "t": "19:00", "g": "Son 32 · Maç 80", "h": "İngiltere", "hc": "ENG", "hf": "icons/england.png", "a": "DK Kongo", "ac": "COD", "af": "icons/dr-congo.png", "city": "Atlanta", "tr": false},
  {"d": "2026-07-01", "t": "23:00", "g": "Son 32 · Maç 82", "h": "Belçika", "hc": "BEL", "hf": "icons/belgium.png", "a": "Senegal", "ac": "SEN", "af": "icons/senegal-flag.png", "city": "Seattle", "tr": false},
  {"d": "2026-07-02", "t": "03:00", "g": "Son 32 · Maç 81", "h": "ABD", "hc": "USA", "hf": "icons/united-states.png", "a": "Bosna Hersek", "ac": "BIH", "af": "icons/bosnia-and-herzegovina.png", "city": "Santa Clara", "tr": false},
  {"d": "2026-07-02", "t": "22:00", "g": "Son 32 · Maç 84", "h": "İspanya", "hc": "ESP", "hf": "icons/spain.png", "a": "Avusturya", "ac": "AUT", "af": "icons/austria.png", "city": "Los Angeles", "tr": false},
  {"d": "2026-07-03", "t": "02:00", "g": "Son 32 · Maç 83", "h": "Portekiz", "hc": "POR", "hf": "icons/portugal.png", "a": "Hırvatistan", "ac": "CRO", "af": "icons/croatia.png", "city": "Toronto", "tr": false},
  {"d": "2026-07-03", "t": "06:00", "g": "Son 32 · Maç 85", "h": "İsviçre", "hc": "SUI", "hf": "icons/switzerland.png", "a": "Cezayir", "ac": "ALG", "af": "icons/algeria.png", "city": "Vancouver", "tr": false},
  {"d": "2026-07-03", "t": "21:00", "g": "Son 32 · Maç 88", "h": "Avustralya", "hc": "AUS", "hf": "icons/australia.png", "a": "Mısır", "ac": "EGY", "af": "icons/egypt.png", "city": "Arlington", "tr": false},
  {"d": "2026-07-04", "t": "01:00", "g": "Son 32 · Maç 86", "h": "Arjantin", "hc": "ARG", "hf": "icons/argentina.png", "a": "Cabo Verde", "ac": "CPV", "af": "icons/cabo-verde.png", "city": "Miami", "tr": false},
  {"d": "2026-07-04", "t": "04:30", "g": "Son 32 · Maç 87", "h": "Kolombiya", "hc": "COL", "hf": "icons/colombia.png", "a": "Gana", "ac": "GHA", "af": "icons/ghana.png", "city": "Kansas City", "tr": false},
  {"d": "2026-07-04", "t": "20:00", "g": "Son 16 · Maç 90", "h": "Maç 73 Galibi", "hc": "?", "hf": "", "a": "Maç 75 Galibi", "ac": "?", "af": "", "city": "Houston", "tr": false},
  {"d": "2026-07-05", "t": "00:00", "g": "Son 16 · Maç 89", "h": "Maç 74 Galibi", "hc": "?", "hf": "", "a": "Maç 77 Galibi", "ac": "?", "af": "", "city": "Philadelphia", "tr": false},
  {"d": "2026-07-05", "t": "23:00", "g": "Son 16 · Maç 91", "h": "Maç 76 Galibi", "hc": "?", "hf": "", "a": "Maç 78 Galibi", "ac": "?", "af": "", "city": "New Jersey", "tr": false},
  {"d": "2026-07-06", "t": "03:00", "g": "Son 16 · Maç 92", "h": "Maç 79 Galibi", "hc": "?", "hf": "", "a": "Maç 80 Galibi", "ac": "?", "af": "", "city": "Mexico City", "tr": false},
  {"d": "2026-07-06", "t": "22:00", "g": "Son 16 · Maç 93", "h": "Maç 83 Galibi", "hc": "?", "hf": "", "a": "Maç 84 Galibi", "ac": "?", "af": "", "city": "Arlington", "tr": false},
  {"d": "2026-07-07", "t": "03:00", "g": "Son 16 · Maç 94", "h": "Maç 81 Galibi", "hc": "?", "hf": "", "a": "Maç 82 Galibi", "ac": "?", "af": "", "city": "Seattle", "tr": false},
  {"d": "2026-07-07", "t": "19:00", "g": "Son 16 · Maç 95", "h": "Maç 86 Galibi", "hc": "?", "hf": "", "a": "Maç 88 Galibi", "ac": "?", "af": "", "city": "Atlanta", "tr": false},
  {"d": "2026-07-07", "t": "23:00", "g": "Son 16 · Maç 96", "h": "Maç 85 Galibi", "hc": "?", "hf": "", "a": "Maç 87 Galibi", "ac": "?", "af": "", "city": "Vancouver", "tr": false},
  {"d": "2026-07-09", "t": "23:00", "g": "Çeyrek Final · Maç 97", "h": "Maç 89 Galibi", "hc": "?", "hf": "", "a": "Maç 90 Galibi", "ac": "?", "af": "", "city": "Foxborough", "tr": false},
  {"d": "2026-07-10", "t": "22:00", "g": "Çeyrek Final · Maç 98", "h": "Maç 93 Galibi", "hc": "?", "hf": "", "a": "Maç 94 Galibi", "ac": "?", "af": "", "city": "Los Angeles", "tr": false},
  {"d": "2026-07-12", "t": "00:00", "g": "Çeyrek Final · Maç 99", "h": "Maç 91 Galibi", "hc": "?", "hf": "", "a": "Maç 92 Galibi", "ac": "?", "af": "", "city": "Miami", "tr": false},
  {"d": "2026-07-12", "t": "04:00", "g": "Çeyrek Final · Maç 100", "h": "Maç 95 Galibi", "hc": "?", "hf": "", "a": "Maç 96 Galibi", "ac": "?", "af": "", "city": "Kansas City", "tr": false},
  {"d": "2026-07-14", "t": "22:00", "g": "Yarı Final · Maç 101", "h": "Maç 97 Galibi", "hc": "?", "hf": "", "a": "Maç 98 Galibi", "ac": "?", "af": "", "city": "Arlington", "tr": false},
  {"d": "2026-07-15", "t": "22:00", "g": "Yarı Final · Maç 102", "h": "Maç 99 Galibi", "hc": "?", "hf": "", "a": "Maç 100 Galibi", "ac": "?", "af": "", "city": "Atlanta", "tr": false},
  {"d": "2026-07-19", "t": "00:00", "g": "3.lük Maçı · Maç 103", "h": "Maç 101 Mağlubu", "hc": "?", "hf": "", "a": "Maç 102 Mağlubu", "ac": "?", "af": "", "city": "Miami", "tr": false},
  {"d": "2026-07-19", "t": "22:00", "g": "Final · Maç 104", "h": "Maç 101 Galibi", "hc": "?", "hf": "", "a": "Maç 102 Galibi", "ac": "?", "af": "", "city": "New Jersey", "tr": false},
];
